### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by James-Thompson-724** [PandemiaProject/pandemia#1]
COMPATIBILITY

- [x] compile C functions for Mac and Linux and test

DOCUMENTATION

- [x] generate documentation

TESTING

- [ ] code tests and assertions, e.g. assertions for all presets and vaccines, e.g. for number_of_rho_immunity_outcomes (assert that number_of_rho_immunity_outcomes is the same for both health model and vaccination model etc...)

PERFORMANCE

- [ ] need to check don't overflow stack when allocating memory in the C functions, if array length (e.g. population size) too big etc...? (move those arrays outside of stack?)
- [ ] optimize runtime and memory usage (padded arrays can be compressed with offsets, for example?)
- [ ] can we use multi-dimensional arrays instead of flat arrays?
- [ ] would using Cython give any performance advantage? are the ctypes overheads significant?

FEATURES

- [ ] rigorous statistical validation methods?
- [ ] make travel matrix represent proportions as opposed to absolute numbers?
- [ ] impact of hospitalization and capacity?
- [ ] testing and contact tracing delays?
- [ ] improved immunity subsampling approach?
- [ ] fast forward remaining sim if total infected is zero?
- [ ] can use malariaAtlas friction surface data and pathfinding to calculate weighting of locations, as opposed to gravity model?
